### ISSUE TITLE
microwatt: Debian GCC toolchain doesn't work

### ISSUE THREAD

**Issue by shenki** [enjoy-digital/litex#1077]
When building a litex soc with microwatt, the following toolchain works fine for a simulation:
```
powerpc64le-linux-gnu-gcc (Debian 11.2.0-9) 11.2.0
```
```
litex_sim --cpu-type=microwatt --cpu-variant=standard+ghdl
```

When targeting the arty FPGA there is no serial output from the BIOS.

Switching to a buildroot toolchain works:
```
powerpc64le-buildroot-linux-musl-gcc.br_real (Buildroot 2020.08-14-ge5a2a90) 9.3.0
```

**Comment by shenki** [comment]
This was fixed with the work in https://github.com/enjoy-digital/litex/issues/1063

**Comment by madscientist159** [comment]
@shenki We're still seeing these symptoms on our side with the latest LiteX/Microwatt versions.  What was the actual fix?  In our case picolibc builds fine but again no serial on the console when run on the ECP5 hardware.
